In [2]:
import numpy as np

In [5]:
a.shape

(3,)

### numpy的属性：

In [2]:
a=np.array([[1,2,3],
            [4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.shape#几行几列：2行3列

(2, 3)

In [5]:
a.ndim#维数：2

2

In [7]:
a.size#几个数

6

### numpy的创建array：

In [23]:
a=np.array([2,23,4])
print(a)

[ 2 23  4]


In [10]:
dd

[ 2 23  4]


In [ ]:
dd

In [24]:
a=np.array([2,23,4],dtype=np.float16)
print(a.dtype)

float16


In [22]:
a=np.array([[2,23,4],
            [2,32,4]])
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [26]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [57]:
a=np.ones((3,4),dtype=np.int16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [93]:
a=np.empty((2,4))
print(a)

[[6.93135145e-310 6.93135145e-310 6.93135145e-310 6.93135145e-310]
 [6.93135145e-310 6.93135145e-310 6.93135145e-310 6.93135145e-310]]


In [95]:
a=np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [98]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
a=np.linspace(1,10,5,dtype=int)
print(a)

[ 1  3  5  7 10]


In [104]:
a=np.linspace(1,10,6).reshape(2,3)
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


### numpy的基础运算：

In [12]:
a=np.array([10,20,30,40])
b=np.arange(4)
print('a:',a)
print('b:',b)
c=a-b
print('c=a-b:',c)
d=a+b
print('d=a+b:',d)
e=b**2
print('e=b^2:',e)

a: [10 20 30 40]
b: [0 1 2 3]
c=a-b: [10 19 28 37]
d=a+b: [10 21 32 43]
e=b^2: [0 1 4 9]


In [14]:
c=10*np.sin(a)
print('c=10sin(c):',c)

c=10sin(c): [-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [17]:
print(b)
print(b<3)
print(b==2)

[0 1 2 3]
[ True  True  True False]
[False False  True False]


In [30]:
a=np.array([[1,1],
            [0,1]])
b=b.reshape(2,2)
print(a,'\n')
print(b,'\n')
c=a*b
print(c,'\n')
d=np.dot(a,b)
print(d,'\n')
d=a.dot(b)
print(d)

[[1 1]
 [0 1]] 

[[0 1]
 [2 3]] 

[[0 1]
 [0 3]] 

[[2 4]
 [2 3]] 

[[2 4]
 [2 3]]


In [44]:
a=np.random.random((2,4))
print(a)
print(a.sum())
print(np.sum(a))
print(a.min())
print(a.max())
print(np.max(a,axis=0))#按行取每列最大的数,axis=1按列取每行
print(a.sum(axis=1))#每行相加


[[0.42594891 0.16292542 0.46667373 0.91623014]
 [0.46308643 0.2180959  0.55481917 0.00741977]]
3.2151994618944735
3.2151994618944735
0.007419771291716781
0.9162301361260944
[0.46308643 0.2180959  0.55481917 0.91623014]
[1.97177819 1.24342127]
