In [4]:
import numpy as np

In [5]:
a.shape

(3,)

### numpy的属性：

In [2]:
a=np.array([[1,2,3],
            [4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.shape#几行几列：2行3列

(2, 3)

In [5]:
a.ndim#维数：2

2

In [7]:
a.size#几个数

6

### numpy的创建array：

In [23]:
a=np.array([2,23,4])
print(a)

[ 2 23  4]


In [10]:
dd

[ 2 23  4]


In [ ]:
dd

In [24]:
a=np.array([2,23,4],dtype=np.float16)
print(a.dtype)

float16


In [22]:
a=np.array([[2,23,4],
            [2,32,4]])
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [26]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [57]:
a=np.ones((3,4),dtype=np.int16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [93]:
a=np.empty((2,4))
print(a)

[[6.93135145e-310 6.93135145e-310 6.93135145e-310 6.93135145e-310]
 [6.93135145e-310 6.93135145e-310 6.93135145e-310 6.93135145e-310]]


In [95]:
a=np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [98]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
a=np.linspace(1,10,5,dtype=int)
print(a)

[ 1  3  5  7 10]


In [104]:
a=np.linspace(1,10,6).reshape(2,3)
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
